const list = [
    {
      id: 1,
      title: "My First Book of Pencil Control",
      author: "by Wonder House Books | 25 April 2018",
      price: 89,
      img: "./Images/images771.jpeg",
      amount: 1,
    },
    {
      id: 2,
      title: "108 Panchatantra Stories",
      author: "by Maple Press  | 1 September 2020",
      price: 98,
      img: "./Images/images771.jpeg",
      amount: 1,
    },
    {
      id: 3,
      title: "Amazing Questions & Answers Science",
      author: "by Om Books Editorial Team  | 25 November 2018",
      price: 143,
      img: "./Images/images771.jpeg",
      amount: 1,
    },
    {
      id: 4,
      title: "My First Book of Pencil Control",
      author: "by Wonder House Books | 25 April 2018",
      price: 57,
      img: "./Images/images771.jpeg",
      amount: 1,
    },
    {
      id: 5,
      title: "My First 1000 Words",
      author: "by Wonder House Books  | 1 January 2018",
      price: 149,
      img: "./Images/images771.jpeg",
      amount: 1,
    },
    {
      id: 6,
      title: "101 Panchatantra Stories for Children",
      author: "by Om Books Editorial Team | 30 September 2020",
      price: 135,
      img: "./Images/images771.jpeg",
      amount: 1,
    },
    {
      id: 7,
      title: "Pre-School Activities Pack ",
      author: "by Om Books Editorial Team  | 1 January 2021",
      price: 693,
      img: "./Images/images771.jpeg",
      amount: 1,
    },
    {
      id: 8,
      title: "Early Learning Library Pack 1",
      author: "by Wonder House Books  | 6 December 2020",
      price: 289,
      img: "./Images/images771.jpeg",
      amount: 1,
    },
    {
      id: 9,
      title: "Blossom Moral Story Book for Kids ",
      author: "by Content Team at Target Publications",
      price: 80,
      img: "./Images/images771.jpeg",
      amount: 1,
    },
    {
      id: 10,
      title: "Brain Activity Book for Kids",
      author: "by Maple Press | 1 September 2021",
      price: 86,
      img: "./Images/images771.jpeg",
      amount: 1,
    },
    {
      id: 11,
      title: "Willy the Silly Panda",
      author: "by Rebecca Smith  | 14 December 2021",
      price: 120,
      img: "./Images/images771.jpeg",
      amount: 1,
    },
    {
      id: 12,
      title: "Grandma's Bag of Stories",
      author: "by Sudha Murty | 1 January 2015",
      price: 157,
      img: "./Images/images771.jpeg",
      amount: 1,
    },
  ];
    export default list;

    